services:
  - type: web
    name: inventario-web
    env: python
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app_web:app --bind 0.0.0.0:$PORT
    envVars:
      - key: HOST
        value: 0.0.0.0
      - key: SECRET_KEY
        value: inventario-uni-2026-cambiar-en-produccion
